# Generated by Django 5.0 on 2024-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
