# Generated by Django 5.0 on 2024-04-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_author_avatar_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnext', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postprevious', to='posts.post'),
        ),
    ]
